name: Deploy

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
